import { getDevAuthState } from '../../dev/auth'
import { getDevScenario, isDevMode } from '../../dev/scenarios'
import type { ApiEnvelope, AvailabilityRequest, AvailableRoom, PageData, Reservation, ReservationRequest } from './types'

export class ApiError extends Error { status: number; code: string; errors: { field: string; reason: string; message: string }[]; constructor(status: number, code: string, message: string, errors: { field: string; reason: string; message: string }[] = []) { super(message); this.status=status; this.code=code; this.errors=errors } }
type MockError={status:number;code:string;message:string;errors:ApiError['errors']};type MockResult<T>={handled:boolean;data?:T;error?:MockError}
const demoRoom: AvailableRoom={room_id:1,room_name:'Ocean Silence Suite',description:'바다와 하늘이 고요하게 만나는 객실',max_guest_count:2,base_price:280000,total_price:560000,nights:2,available:true,remaining_count:2}
const demoReservation: Reservation={resv_id:101,reservation_number:'RSV-20260912-A13F59C',room_name:demoRoom.room_name,room_number:'203',check_in_date:'2026-09-12',check_out_date:'2026-09-14',guest_count:2,nights:2,base_price:280000,total_price:560000,status:'RESERVED',created_at:'2026-09-01 14:22'}
const protectedRequest=(url:string,init?:RequestInit)=>url.startsWith('/resv/me')||(/^\/resv\/\d/.test(url))||init?.method==='POST'
async function request<T>(url:string,init?:RequestInit):Promise<T>{const mocked=await devResponse<T>(url,init);if(mocked.handled){if(mocked.error)throw new ApiError(mocked.error.status,mocked.error.code,mocked.error.message,mocked.error.errors);return mocked.data as T}const response=await fetch(`/api${url}`,{credentials:'include',headers:{'Content-Type':'application/json',...init?.headers},...init});const raw=await response.text();let body:ApiEnvelope<T & {errors?:ApiError['errors']}>;try{body=JSON.parse(raw) as ApiEnvelope<T & {errors?:ApiError['errors']}>}catch{throw new ApiError(response.status,'API_INVALID_RESPONSE','API 서버 응답을 확인할 수 없습니다. 백엔드 연결 또는 개발 시나리오를 확인해 주세요.')}if(!response.ok)throw new ApiError(response.status,body.code,body.message,body.data?.errors??[]);return body.data}
async function devResponse<T>(url:string,init?:RequestInit):Promise<MockResult<T>>{if(!isDevMode)return{handled:false};const error=(status:number,code:string,message:string,errors:ApiError['errors']=[]):MockResult<T>=>({handled:true,error:{status,code,message,errors}});if(getDevAuthState()==='guest'&&protectedRequest(url,init))return error(401,'AUTH_UNAUTHORIZED','로그인이 필요합니다.');const scenario=getDevScenario();if(scenario==='live')return{handled:false};if(scenario==='loading'){await new Promise(resolve=>setTimeout(resolve,1500));return{handled:false}}if(scenario==='validation')return error(400,'VALIDATION_ERROR','입력 값을 확인해 주세요.',[{field:'check_out_date',reason:'INVALID_RANGE',message:'체크아웃은 체크인 이후여야 합니다.'}]);if(scenario==='unauthorized')return error(401,'AUTH_UNAUTHORIZED','로그인이 필요합니다.');if(scenario==='forbidden')return error(403,'AUTH_FORBIDDEN','권한이 없습니다.');if(scenario==='not-found')return error(404,'RESV_NOT_FOUND','예약을 찾을 수 없습니다.');if(scenario==='room-conflict'&&init?.method==='POST')return error(409,'ROOM_NOT_AVAILABLE','방금 다른 예약이 발생했습니다.');if(scenario==='cancel-conflict'&&url.endsWith('/cancel'))return error(409,'RESV_CANNOT_CANCEL','현재 예약은 취소할 수 없습니다.');if(scenario==='empty'){if(url.startsWith('/resv?'))return{handled:true,data:[] as T};if(url.startsWith('/resv/me'))return{handled:true,data:{content:[],total_pages:0,number:0} as T}}if(scenario==='demo'){if(url.startsWith('/resv?'))return{handled:true,data:[demoRoom] as T};if(url.startsWith('/resv/me'))return{handled:true,data:{content:[demoReservation],total_pages:1,number:0} as T};if(init?.method==='POST')return{handled:true,data:demoReservation as T};if(url.endsWith('/cancel'))return{handled:true,data:{...demoReservation,status:'CANCELLED',cancelled_at:'2026-09-02 10:14'} as T};if(url.startsWith('/resv/'))return{handled:true,data:demoReservation as T}}return{handled:false}}
export const reservationApi={availability:(p:AvailabilityRequest)=>request<AvailableRoom[]>(`/resv?${new URLSearchParams({check_in_date:p.check_in_date,check_out_date:p.check_out_date,guest_count:String(p.guest_count)})}`),create:(data:ReservationRequest)=>request<Reservation>('/resv',{method:'POST',body:JSON.stringify(data)}),mine:(page=0)=>request<PageData<Reservation>>(`/resv/me?page_num=${page}`),detail:(id:string)=>request<Reservation>(`/resv/${id}`),cancel:(id:string)=>request<Reservation>(`/resv/${id}/cancel`,{method:'PATCH'})}
